# ============================================================
# main.py — Pipeline Entry Point
# ============================================================
# This is the SINGLE ENTRY POINT for the Semantic Knowledge Pipeline.
# It orchestrates the full flow:
#   1. SCRAPE — Use Playwright to fetch web pages
#   2. VALIDATE — Pydantic ensures data quality
#   3. STORE — SQLAlchemy persists to PostgreSQL
#
# Run: python main.py
#
# This follows the "Explain-Then-Build" principle:
#   Each phase is clearly separated so you can see exactly
#   what happens at each step of the data pipeline.
# ============================================================

import asyncio
import logging
import sys

from database.connection import engine, Base, get_db_session
from database.models import RawArticle, KnowledgeTripleDB, CurriculumDB, ModuleDB, LessonDB
from scraper.mdn_scraper import MdnScraper
from pipeline.text_chunker import chunk_text
from pipeline.triple_extractor import TripleExtractor
from pipeline.curriculum_agent import CurriculumAgent

# ----------------------------------------------------------
# LOGGING CONFIGURATION
# ----------------------------------------------------------
# We configure the root logger here (in main) because this is
# the entry point. All other modules use logging.getLogger(__name__)
# which inherits this configuration.
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ----------------------------------------------------------
# TARGET URLS
# ----------------------------------------------------------
# These are the MDN pages we want to scrape and store.
# In a future phase, this could be:
#   - Read from a config file
#   - Generated by a sitemap crawler
#   - Passed as command-line arguments
MDN_URLS = [
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises",
]


async def run_pipeline() -> None:
    """
    Main pipeline: Scrape → Validate → Store.

    This is the orchestrator that ties all our modules together.
    Each step is clearly separated so you can see the data flow.
    """
    logger.info("=" * 60)
    logger.info("SEMANTIC KNOWLEDGE PIPELINE — Starting")
    logger.info("=" * 60)

    # ----------------------------------------------------------
    # STEP 1: Ensure database is ready
    # ----------------------------------------------------------
    # Base.metadata.create_all scans all SQLAlchemy models that
    # inherit from Base and creates the corresponding tables
    # in PostgreSQL (if they don't already exist).
    logger.info("Ensuring database tables exist...")
    Base.metadata.create_all(engine)
    logger.info("Database ready.")

    # ----------------------------------------------------------
    # STEP 2: Scrape web pages
    # ----------------------------------------------------------
    # The MdnScraper handles:
    #   - Launching headless Chromium via Playwright
    #   - Navigating to each URL with retries + exponential backoff
    #   - Extracting title + content using MDN-specific CSS selectors
    #   - Validating each article through our Pydantic model
    #   - Rate limiting (2s between requests — be polite!)
    logger.info(f"Scraping {len(MDN_URLS)} MDN pages...")
    scraper = MdnScraper()
    articles = await scraper.scrape(MDN_URLS)
    logger.info(f"Scraping complete: {len(articles)}/{len(MDN_URLS)} pages successful")

    if not articles:
        logger.warning("No articles scraped. Exiting.")
        return

    # ----------------------------------------------------------
    # STEP 3: Store in PostgreSQL
    # ----------------------------------------------------------
    # We use a single database session for all inserts.
    # The UNIQUE constraint on raw_articles.url prevents duplicates —
    # if we run this twice, the second run skips already-stored URLs.
    logger.info("Storing articles in PostgreSQL...")
    stored_count = 0
    skipped_count = 0

    with get_db_session() as session:
        for article in articles:
            # Check if this URL was already scraped (idempotency)
            existing = session.query(RawArticle).filter_by(
                url=str(article.url)
            ).first()

            if existing:
                logger.info(f"  SKIPPED (duplicate): {article.title[:50]}")
                skipped_count += 1
                continue

            # Convert Pydantic model → SQLAlchemy ORM object
            # This is where the data crosses from "validation land" to "storage land"
            row = RawArticle(
                title=article.title,
                url=str(article.url),
                raw_text=article.raw_text,
                source_site=article.source_site,
            )
            session.add(row)
            logger.info(f"  STORED: {article.title[:60]}")
            stored_count += 1

        # Commit all inserts in a single transaction.
        # If ANY insert fails (e.g., constraint violation), ALL are rolled back.
        session.commit()

    # ----------------------------------------------------------
    # STEP 4: Extract Knowledge Triples with LLM
    # ----------------------------------------------------------
    # Now we take all raw articles from the database and feed them
    # through our LLM pipeline:
    #   Raw text → Chunk → Send to Gemma 4 → Parse JSON → Validate → Store
    #
    # WHY READ FROM DB (not use the scraped articles directly)?
    #   - Idempotency: we can re-run just this step without re-scraping
    #   - The DB is our "source of truth" for raw data
    logger.info("=" * 60)
    logger.info("STEP 4: LLM KNOWLEDGE EXTRACTION (Gemma 4 via Ollama)")
    logger.info("=" * 60)

    # Read ALL articles from the database (not just newly scraped ones)
    with get_db_session() as session:
        all_articles = session.query(RawArticle).all()

    logger.info(f"Found {len(all_articles)} articles to process")

    # Initialize the LLM extractor (connects to local Ollama)
    extractor = TripleExtractor(
        model_name="gemma4:26b",
        num_ctx=32768,       # 32K token context window
        temperature=0.1,     # Nearly deterministic for factual extraction
        max_retries=3,
    )

    total_triples = 0

    for article_row in all_articles:
        logger.info(f"\nProcessing: {article_row.title} ({len(article_row.raw_text)} chars)")

        # ----------------------------------------------------------
        # 4a: CHUNK the article text
        # ----------------------------------------------------------
        # Split into ~4000 char chunks with 400 char overlap.
        # Most of our articles are ~7000 chars → 2 chunks.
        chunks = chunk_text(
            article_row.raw_text,
            chunk_size=4000,
            overlap=400,
        )
        logger.info(f"  Split into {len(chunks)} chunk(s)")

        # ----------------------------------------------------------
        # 4b: EXTRACT triples from chunks using Gemma 4
        # ----------------------------------------------------------
        result = await extractor.extract_from_chunks(
            chunks=chunks,
            source_url=article_row.url,
        )
        logger.info(f"  Extracted {len(result.triples)} triples")

        if not result.triples:
            logger.warning(f"  No triples extracted from: {article_row.title}")
            continue

        # ----------------------------------------------------------
        # 4c: STORE validated triples in PostgreSQL
        # ----------------------------------------------------------
        # Each Pydantic-validated KnowledgeTriple → SQLAlchemy KnowledgeTripleDB row
        with get_db_session() as session:
            for triple in result.triples:
                # Check if this exact triple already exists (deduplication)
                existing = session.query(KnowledgeTripleDB).filter_by(
                    subject=triple.subject,
                    predicate=triple.predicate,
                    object_value=triple.object_,
                    source_url=str(triple.source_url),
                ).first()

                if existing:
                    logger.debug(f"  SKIP (duplicate): {triple.subject} -[{triple.predicate}]-> {triple.object_}")
                    continue

                row = KnowledgeTripleDB(
                    subject=triple.subject,
                    predicate=triple.predicate,
                    object_value=triple.object_,
                    source_url=str(triple.source_url),
                    confidence=triple.confidence,
                )
                session.add(row)
                logger.info(f"  + {triple.subject} -[{triple.predicate}]-> {triple.object_} (conf={triple.confidence})")
                total_triples += 1

            session.commit()

    # ----------------------------------------------------------
    # STEP 5: Generate Curriculum from Knowledge Graph
    # ----------------------------------------------------------
    # This is the CORE PRODUCT FEATURE — our AI agent reads all the
    # triples and articles from the database, then generates a structured
    # learning curriculum.
    #
    # WHY READ FROM DB AGAIN?
    #   - We want ALL triples, not just the ones extracted this run
    #   - The knowledge graph grows over time as we scrape more sources
    #   - The agent can generate richer curricula with more data
    logger.info("=" * 60)
    logger.info("STEP 5: CURRICULUM GENERATION (CurriculumAgent)")
    logger.info("=" * 60)

    # Gather context from the knowledge graph
    with get_db_session() as session:
        all_triples = session.query(KnowledgeTripleDB).all()
        all_raw_articles = session.query(RawArticle).all()

        # Convert SQLAlchemy objects to dicts for the agent
        # (the agent doesn't need to know about SQLAlchemy)
        triples_data = [
            {
                "subject": t.subject,
                "predicate": t.predicate,
                "object_value": t.object_value,
                "confidence": t.confidence,
            }
            for t in all_triples
        ]
        articles_data = [
            {
                "title": a.title,
                "url": a.url,
                "raw_text": a.raw_text,
            }
            for a in all_raw_articles
        ]

    logger.info(f"Context: {len(triples_data)} triples, {len(articles_data)} articles")

    # Initialize and run the Curriculum Agent
    agent = CurriculumAgent(
        model_name="gemma4:26b",
        temperature=0.3,     # Slightly creative for varied curricula
        max_retries=3,
    )

    curriculum = agent.generate_curriculum(
        topic="Async JavaScript",
        triples=triples_data,
        articles=articles_data,
        target_audience="Junior to mid-level JavaScript developers",
        difficulty="intermediate",
    )

    if curriculum:
        logger.info(f"Curriculum generated: '{curriculum.title}'")

        # --- Store the validated curriculum in PostgreSQL ---
        # We create the curriculum row first, then modules, then lessons.
        # SQLAlchemy handles the relationships (foreign keys) automatically.
        with get_db_session() as session:
            # Pydantic Curriculum → SQLAlchemy CurriculumDB
            curriculum_row = CurriculumDB(
                title=curriculum.title,
                description=curriculum.description,
                topic=curriculum.topic,
                target_audience=curriculum.target_audience,
                difficulty=curriculum.difficulty,
                model_name=curriculum.model_name,
            )
            session.add(curriculum_row)
            session.flush()  # Flush to get the auto-generated curriculum_row.id

            total_modules = 0
            total_lessons = 0

            for mod in curriculum.modules:
                # Pydantic Module → SQLAlchemy ModuleDB
                module_row = ModuleDB(
                    title=mod.title,
                    description=mod.description,
                    order_index=mod.order_index,
                    curriculum_id=curriculum_row.id,
                )
                session.add(module_row)
                session.flush()  # Flush to get module_row.id

                for lesson in mod.lessons:
                    # Pydantic Lesson → SQLAlchemy LessonDB
                    lesson_row = LessonDB(
                        title=lesson.title,
                        description=lesson.description,
                        order_index=lesson.order_index,
                        learning_objectives=lesson.learning_objectives,
                        prerequisites=lesson.prerequisites,
                        source_urls=lesson.source_urls,
                        module_id=module_row.id,
                    )
                    session.add(lesson_row)
                    total_lessons += 1

                total_modules += 1

            session.commit()
            logger.info(f"Stored curriculum: {total_modules} modules, {total_lessons} lessons")
    else:
        logger.error("Curriculum generation failed after all retries")

    # ----------------------------------------------------------
    # STEP 6: Final Summary
    # ----------------------------------------------------------
    logger.info("=" * 60)
    logger.info("PIPELINE COMPLETE")
    logger.info(f"  Scraped:  {len(articles)}/{len(MDN_URLS)}")
    logger.info(f"  Stored:   {stored_count} new articles")
    logger.info(f"  Skipped:  {skipped_count} duplicate articles")
    logger.info(f"  Triples:  {total_triples} new knowledge triples")
    logger.info("=" * 60)

    # Show what's in the database now
    with get_db_session() as session:
        all_rows = session.query(RawArticle).all()
        all_triples = session.query(KnowledgeTripleDB).all()
        all_curricula = session.query(CurriculumDB).all()

        print(f"\n📚 Database Summary:")
        print(f"  Articles: {len(all_rows)}")
        print(f"  Knowledge Triples: {len(all_triples)}")
        print(f"  Curricula: {len(all_curricula)}")
        print()

        for r in all_rows:
            print(f"  [{r.id}] {r.title} ({r.source_site})")
        print()
        for t in all_triples:
            print(f"  {t.subject} -[{t.predicate}]-> {t.object_value} (conf={t.confidence})")
        print()

        # Pretty-print generated curricula
        for c in all_curricula:
            print(f"  📖 Curriculum: {c.title}")
            print(f"     Topic: {c.topic} | Difficulty: {c.difficulty}")
            print(f"     Audience: {c.target_audience}")
            for m in sorted(c.modules, key=lambda x: x.order_index):
                print(f"     📂 Module {m.order_index}: {m.title}")
                for l in sorted(m.lessons, key=lambda x: x.order_index):
                    print(f"        📄 Lesson {l.order_index}: {l.title}")
                    for obj in l.learning_objectives:
                        print(f"           - {obj}")
            print()


if __name__ == "__main__":
    # asyncio.run() is the standard way to run an async function
    # from a synchronous entry point. It creates an event loop,
    # runs our coroutine, then closes the loop.
    asyncio.run(run_pipeline())