"""Phase 9A: New data model - domains, topics, concepts, etc.

Revision ID: 0001
Revises:
Create Date: 2026-04-16 03:11:57.344883

Adds 7 new tables for the educational knowledge graph:
  - domains, topics, concepts, concept_relationships,
    examples, exercises, source_sections
Also adds topic_id FK to raw_articles table.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('source_urls', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'slug', name='uq_topics_domain_slug')
    )
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('theory_text', sa.Text(), nullable=True),
    sa.Column('simple_explanation', sa.Text(), nullable=True),
    sa.Column('simple_explanation_source', sa.String(length=50), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=False),
    sa.Column('common_mistakes', sa.JSON(), nullable=False),
    sa.Column('related_concepts_cache', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'slug', name='uq_concepts_topic_slug')
    )
    op.create_table('concept_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_concept_id', sa.Integer(), nullable=False),
    sa.Column('to_concept_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.CheckConstraint("relationship_type IN ('requires', 'enables', 'is_a', 'part_of', 'related_to', 'contrasts_with', 'built_on')", name='ck_concept_relationships_type'),
    sa.CheckConstraint('strength >= 0.0 AND strength <= 1.0', name='ck_concept_relationships_strength'),
    sa.ForeignKeyConstraint(['from_concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_concept_id', 'to_concept_id', 'relationship_type', name='uq_concept_relationships_edge')
    )
    op.create_table('examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('solution_code', sa.Text(), nullable=False),
    sa.Column('hints', sa.JSON(), nullable=False),
    sa.Column('test_cases', sa.JSON(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name='ck_exercises_difficulty'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('heading_level', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('concept_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['raw_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('raw_articles', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'raw_articles', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_articles', type_='foreignkey')
    op.drop_column('raw_articles', 'topic_id')
    op.drop_table('source_sections')
    op.drop_table('exercises')
    op.drop_table('examples')
    op.drop_table('concept_relationships')
    op.drop_table('concepts')
    op.drop_table('topics')
    op.drop_table('domains')
    # ### end Alembic commands ###
